version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
    kafka:
        image: wurstmeister/kafka:1.0.0
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_BATCH_SIZE: 0
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 600000
            KAFKA_CREATE_TOPICS: "project:1:1"
        ports:
            - 9092:9092  # Uncomment to make Kafka available externally
