version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
    kafka:
        image: wurstmeister/kafka
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "project:1:1"
        ports:
            - 9092:9092  # Uncomment to make Kafka available externally
